#!/bin/bash
mkdir -p ./audio_1/spectrogram_diff/mp3
mkdir -p ./audio_1/spectrogram_diff/aac_lc
mkdir -p ./audio_1/spectrogram_diff/aac_he_v1
mkdir -p ./audio_1/spectrogram_diff/aac_he_v2
mkdir -p ./audio_1/spectrogram_diff/vorbis
mkdir -p ./audio_1/spectrogram_diff/opus
mkdir -p ./audio_2/spectrogram_diff/mp3
mkdir -p ./audio_2/spectrogram_diff/aac_lc
mkdir -p ./audio_2/spectrogram_diff/aac_he_v1
mkdir -p ./audio_2/spectrogram_diff/aac_he_v2
mkdir -p ./audio_2/spectrogram_diff/vorbis
mkdir -p ./audio_2/spectrogram_diff/opus
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_16k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_24k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_32k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_48k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_64k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_80k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_96k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_112k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_128k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_160k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_192k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v1/aac_he_v1_256k.png ./audio_1/spectrogram_diff/aac_he_v1/aac_he_v1_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_16k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_24k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_32k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_48k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_64k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_80k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_96k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_112k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_128k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_160k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_192k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_he_v2/aac_he_v2_256k.png ./audio_1/spectrogram_diff/aac_he_v2/aac_he_v2_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_16k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_24k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_32k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_48k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_64k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_80k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_96k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_112k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_128k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_160k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_192k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/aac_lc/aac_lc_256k.png ./audio_1/spectrogram_diff/aac_lc/aac_lc_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_32k.png ./audio_1/spectrogram_diff/mp3/mp3_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_48k.png ./audio_1/spectrogram_diff/mp3/mp3_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_64k.png ./audio_1/spectrogram_diff/mp3/mp3_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_80k.png ./audio_1/spectrogram_diff/mp3/mp3_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_96k.png ./audio_1/spectrogram_diff/mp3/mp3_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_112k.png ./audio_1/spectrogram_diff/mp3/mp3_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_128k.png ./audio_1/spectrogram_diff/mp3/mp3_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_160k.png ./audio_1/spectrogram_diff/mp3/mp3_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_192k.png ./audio_1/spectrogram_diff/mp3/mp3_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/mp3/mp3_256k.png ./audio_1/spectrogram_diff/mp3/mp3_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_16k.png ./audio_1/spectrogram_diff/opus/opus_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_24k.png ./audio_1/spectrogram_diff/opus/opus_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_32k.png ./audio_1/spectrogram_diff/opus/opus_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_48k.png ./audio_1/spectrogram_diff/opus/opus_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_64k.png ./audio_1/spectrogram_diff/opus/opus_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_80k.png ./audio_1/spectrogram_diff/opus/opus_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_96k.png ./audio_1/spectrogram_diff/opus/opus_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_112k.png ./audio_1/spectrogram_diff/opus/opus_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_128k.png ./audio_1/spectrogram_diff/opus/opus_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_160k.png ./audio_1/spectrogram_diff/opus/opus_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_192k.png ./audio_1/spectrogram_diff/opus/opus_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/opus/opus_256k.png ./audio_1/spectrogram_diff/opus/opus_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_32k.png ./audio_1/spectrogram_diff/vorbis/vorbis_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_48k.png ./audio_1/spectrogram_diff/vorbis/vorbis_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_64k.png ./audio_1/spectrogram_diff/vorbis/vorbis_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_80k.png ./audio_1/spectrogram_diff/vorbis/vorbis_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_96k.png ./audio_1/spectrogram_diff/vorbis/vorbis_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_112k.png ./audio_1/spectrogram_diff/vorbis/vorbis_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_128k.png ./audio_1/spectrogram_diff/vorbis/vorbis_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_160k.png ./audio_1/spectrogram_diff/vorbis/vorbis_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_192k.png ./audio_1/spectrogram_diff/vorbis/vorbis_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_1.png ./audio_1/spectrogram/vorbis/vorbis_256k.png ./audio_1/spectrogram_diff/vorbis/vorbis_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_16k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_24k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_32k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_48k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_64k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_80k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_96k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_112k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_128k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_160k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_192k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v1/aac_he_v1_256k.png ./audio_2/spectrogram_diff/aac_he_v1/aac_he_v1_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_16k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_24k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_32k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_48k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_64k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_80k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_96k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_112k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_128k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_160k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_192k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_he_v2/aac_he_v2_256k.png ./audio_2/spectrogram_diff/aac_he_v2/aac_he_v2_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_16k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_24k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_32k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_48k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_64k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_80k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_96k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_112k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_128k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_160k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_192k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/aac_lc/aac_lc_256k.png ./audio_2/spectrogram_diff/aac_lc/aac_lc_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_32k.png ./audio_2/spectrogram_diff/mp3/mp3_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_48k.png ./audio_2/spectrogram_diff/mp3/mp3_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_64k.png ./audio_2/spectrogram_diff/mp3/mp3_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_80k.png ./audio_2/spectrogram_diff/mp3/mp3_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_96k.png ./audio_2/spectrogram_diff/mp3/mp3_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_112k.png ./audio_2/spectrogram_diff/mp3/mp3_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_128k.png ./audio_2/spectrogram_diff/mp3/mp3_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_160k.png ./audio_2/spectrogram_diff/mp3/mp3_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_192k.png ./audio_2/spectrogram_diff/mp3/mp3_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/mp3/mp3_256k.png ./audio_2/spectrogram_diff/mp3/mp3_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_16k.png ./audio_2/spectrogram_diff/opus/opus_16k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_24k.png ./audio_2/spectrogram_diff/opus/opus_24k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_32k.png ./audio_2/spectrogram_diff/opus/opus_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_48k.png ./audio_2/spectrogram_diff/opus/opus_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_64k.png ./audio_2/spectrogram_diff/opus/opus_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_80k.png ./audio_2/spectrogram_diff/opus/opus_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_96k.png ./audio_2/spectrogram_diff/opus/opus_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_112k.png ./audio_2/spectrogram_diff/opus/opus_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_128k.png ./audio_2/spectrogram_diff/opus/opus_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_160k.png ./audio_2/spectrogram_diff/opus/opus_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_192k.png ./audio_2/spectrogram_diff/opus/opus_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/opus/opus_256k.png ./audio_2/spectrogram_diff/opus/opus_256k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_32k.png ./audio_2/spectrogram_diff/vorbis/vorbis_32k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_48k.png ./audio_2/spectrogram_diff/vorbis/vorbis_48k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_64k.png ./audio_2/spectrogram_diff/vorbis/vorbis_64k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_80k.png ./audio_2/spectrogram_diff/vorbis/vorbis_80k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_96k.png ./audio_2/spectrogram_diff/vorbis/vorbis_96k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_112k.png ./audio_2/spectrogram_diff/vorbis/vorbis_112k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_128k.png ./audio_2/spectrogram_diff/vorbis/vorbis_128k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_160k.png ./audio_2/spectrogram_diff/vorbis/vorbis_160k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_192k.png ./audio_2/spectrogram_diff/vorbis/vorbis_192k.jpg
magick composite -quality 90 -compose difference ./ORIGINAL_AUDIO_2.png ./audio_2/spectrogram/vorbis/vorbis_256k.png ./audio_2/spectrogram_diff/vorbis/vorbis_256k.jpg
